services:
  api:
    build: .  
    # entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      # Mount application code for live reloading
      - ./app:/project/app
    deploy:
      resources:
        limits:
          # container memory(RAM) usage limit
          memory: 512M
