"""added owner for the item

Revision ID: 578a6a8ce5fe
Revises: b01830eee300
Create Date: 2025-11-01 20:21:55.355411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "578a6a8ce5fe"
down_revision: Union[str, Sequence[str], None] = "b01830eee300"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("owner", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "owner")
    # ### end Alembic commands ###
